package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const hostGatewayExtraHost = "host.docker.internal:host-gateway"

// AuthThemeContainerPath is the in-container path for a bind-mounted OpenAuth
// Theme JSON. Matches plat5dev/auth (AUTH_THEME_FILE=/config/theme.json).
const AuthThemeContainerPath = "/config/theme.json"

// OverrideOpts controls optional bits written into CLI compose overrides.
type OverrideOpts struct {
	// HostGateway adds extra_hosts host.docker.internal:host-gateway on services
	// that need to reach the host (e.g. OTLP to a host-published collector).
	HostGateway bool
	// AuthThemeFile is the host path of an OpenAuth Theme JSON to bind-mount
	// into the Auth issuer at AuthThemeContainerPath. Empty = no mount.
	AuthThemeFile string
}

// WritePlat5Override writes a compose override that remaps gateway and registry host ports.
// Uses Compose !override so base ports are replaced, not appended.
func WritePlat5Override(path string, gatewayPort, registryPort int, opts OverrideOpts) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by plat5 CLI — do not edit
services:
  gateway:
    ports: !override
      - "%d:5001"
`, gatewayPort)
	if opts.HostGateway {
		fmt.Fprintf(&b, "    extra_hosts:\n      - %q\n", hostGatewayExtraHost)
	}
	fmt.Fprintf(&b, `  route-registry:
    ports: !override
      - "%d:5002"
`, registryPort)
	if opts.HostGateway {
		fmt.Fprintf(&b, `    extra_hosts:
      - %q
  identity:
    extra_hosts:
      - %q
`, hostGatewayExtraHost, hostGatewayExtraHost)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// WriteAuthOverride remaps the Plat5 Auth issuer host port.
func WriteAuthOverride(path string, authPort int, opts OverrideOpts) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by plat5 CLI — do not edit
services:
  issuer:
    ports: !override
      - "%d:5000"
`, authPort)
	if opts.HostGateway {
		fmt.Fprintf(&b, "    extra_hosts:\n      - %q\n", hostGatewayExtraHost)
	}
	if opts.AuthThemeFile != "" {
		fmt.Fprintf(&b, "    volumes:\n      - %q\n", opts.AuthThemeFile+":"+AuthThemeContainerPath+":ro")
		fmt.Fprintf(&b, "    environment:\n      AUTH_THEME_FILE: %s\n", AuthThemeContainerPath)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// ObservabilityPorts are host ports published for the local LGTM stack.
type ObservabilityPorts struct {
	Grafana  int
	OTLPGRPC int
	OTLPHTTP int
	Alloy    int
}

// Plat5NetworkName is the Docker network Compose creates for a Plat5 project.
// The compose file's network key is "plat5" and does not set an explicit name.
// The CLI sets the project with -p, which wins over the file's top-level name,
// so the network is <project>_plat5. Operator joins that name. It is not discovered.
func Plat5NetworkName(composeProject string) string {
	return composeProject + "_plat5"
}

// Local staff IdP clients. Dex puts the client id in the access token's aud,
// so both ids are the Operator gateway's AUTH_AUDIENCES.
const (
	// OperatorCLIClientID is a confidential client for scripts (password grant).
	OperatorCLIClientID     = "operator-cli"
	OperatorCLIClientSecret = "operator-cli-secret"
	// OperatorConsoleClientID is a public PKCE client for browser consoles.
	OperatorConsoleClientID = "operator-console"
)

// OperatorOverride is what start knows about the local Operator stack.
type OperatorOverride struct {
	Port           int      // host port for the gateway (container 5004)
	IdPPort        int      // host port for Dex (container 5556)
	IssuerURL      string   // http://localhost:<IdPPort>/dex
	AllowedOrigins []string // browser consoles
	Plat5Network   string   // <project>_plat5
	DexConfig      string   // host path of the generated Dex config
}

// WriteOperatorOverride wires the Operator stack: host ports, the gateway's IdP settings,
// the generated Dex config, and the Plat5 network so the image route list can dial
// identity:3000. Identity is not published. Routes are not rewritten.
// The same override fits the embedded bundle and operator/compose in path mode.
func WriteOperatorOverride(path string, o OperatorOverride) error {
	if o.Plat5Network == "" {
		return fmt.Errorf("operator override: empty plat5 network name")
	}
	if o.DexConfig == "" {
		return fmt.Errorf("operator override: empty dex config path")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by plat5 CLI — do not edit
# Operator joins the Plat5 network to dial identity:3000. Dex is the local staff IdP.
networks:
  plat5:
    external: true
    name: %q
services:
  operator:
    ports: !override
      - "%d:5004"
    networks:
      - default
      - plat5
    environment:
      ROUTES_FILE: /routes.yml
      AUTH_ISSUER: %q
      AUTH_JWKS_URI: http://dex:5556/dex/keys
      AUTH_AUDIENCES: %q
      ALLOWED_ORIGINS: %q
  dex:
    ports: !override
      - "%d:5556"
    volumes: !override
      - %q
`,
		o.Plat5Network,
		o.Port,
		o.IssuerURL,
		OperatorCLIClientID+","+OperatorConsoleClientID,
		strings.Join(o.AllowedOrigins, ","),
		o.IdPPort,
		o.DexConfig+":/etc/dex/config.yaml:ro",
	)
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// devPasswordHash is bcrypt("password"), the local staff login. Not for production.
const devPasswordHash = "$2a$10$PU91IMgGuOpYIgbkSRoL7ugHIFRkH2b9F0ssd90gVkXaiEDTT2qWq"

// WriteOperatorDexConfig writes the local staff IdP config: one dev login, a script
// client, and a public PKCE client that redirects to <origin>/callback on each origin.
func WriteOperatorDexConfig(path, issuerURL, email string, allowedOrigins []string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by plat5 CLI — do not edit
# Local staff IdP for Operator. Not for production.
issuer: %q
storage:
  type: memory
web:
  http: 0.0.0.0:5556
  allowedOrigins:
`, issuerURL)
	for _, o := range allowedOrigins {
		fmt.Fprintf(&b, "    - %q\n", o)
	}
	fmt.Fprintf(&b, `oauth2:
  passwordConnector: local
  skipApprovalScreen: true
enablePasswordDB: true
staticPasswords:
  - email: %q
    hash: %q
    username: staff
    userID: 6c1f3c3e-5f8b-4f0e-9d55-7d3c1d2b9a10
staticClients:
  - id: %q
    name: Operator CLI
    secret: %q
  - id: %q
    name: Operator Console
    public: true
    redirectURIs:
`, email, devPasswordHash, OperatorCLIClientID, OperatorCLIClientSecret, OperatorConsoleClientID)
	for _, o := range allowedOrigins {
		fmt.Fprintf(&b, "      - %q\n", strings.TrimRight(o, "/")+"/callback")
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// WriteObservabilityOverride remaps Grafana / Alloy host ports (loopback-bound).
func WriteObservabilityOverride(path string, p ObservabilityPorts) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	body := fmt.Sprintf(`# Generated by plat5 CLI — do not edit
services:
  grafana:
    ports: !override
      - "127.0.0.1:%d:3000"
  alloy:
    ports: !override
      - "127.0.0.1:%d:4317"
      - "127.0.0.1:%d:4318"
      - "127.0.0.1:%d:12345"
`, p.Grafana, p.OTLPGRPC, p.OTLPHTTP, p.Alloy)
	return os.WriteFile(path, []byte(body), 0o644)
}
