package compose

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const hostGatewayExtraHost = "host.docker.internal:host-gateway"

// AuthThemeContainerPath is the in-container path for a bind-mounted OpenAuth
// Theme JSON. Matches plat5dev/auth (AUTH_THEME_FILE=/config/theme.json).
const AuthThemeContainerPath = "/config/theme.json"

// OverrideOpts controls optional bits written into CLI compose overrides.
type OverrideOpts struct {
	// HostGateway adds extra_hosts host.docker.internal:host-gateway on services
	// that need to reach the host (e.g. OTLP to a host-published collector).
	HostGateway bool
	// AuthThemeFile is the host path of an OpenAuth Theme JSON to bind-mount
	// into the Auth issuer at AuthThemeContainerPath. Empty = no mount.
	AuthThemeFile string
}

// WritePlat5Override writes a compose override that remaps gateway and registry host ports.
// Uses Compose !override so base ports are replaced, not appended.
func WritePlat5Override(path string, gatewayPort, registryPort int, opts OverrideOpts) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by plat5 CLI — do not edit
services:
  gateway:
    ports: !override
      - "%d:5001"
`, gatewayPort)
	if opts.HostGateway {
		fmt.Fprintf(&b, "    extra_hosts:\n      - %q\n", hostGatewayExtraHost)
	}
	fmt.Fprintf(&b, `  route-registry:
    ports: !override
      - "%d:5002"
`, registryPort)
	if opts.HostGateway {
		fmt.Fprintf(&b, `    extra_hosts:
      - %q
  identity:
    extra_hosts:
      - %q
`, hostGatewayExtraHost, hostGatewayExtraHost)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// WriteAuthOverride remaps the Plat5 Auth issuer host port.
func WriteAuthOverride(path string, authPort int, opts OverrideOpts) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	var b strings.Builder
	fmt.Fprintf(&b, `# Generated by plat5 CLI — do not edit
services:
  issuer:
    ports: !override
      - "%d:5000"
`, authPort)
	if opts.HostGateway {
		fmt.Fprintf(&b, "    extra_hosts:\n      - %q\n", hostGatewayExtraHost)
	}
	if opts.AuthThemeFile != "" {
		fmt.Fprintf(&b, "    volumes:\n      - %q\n", opts.AuthThemeFile+":"+AuthThemeContainerPath+":ro")
		fmt.Fprintf(&b, "    environment:\n      AUTH_THEME_FILE: %s\n", AuthThemeContainerPath)
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// ObservabilityPorts are host ports published for the local LGTM stack.
type ObservabilityPorts struct {
	Grafana  int
	OTLPGRPC int
	OTLPHTTP int
	Alloy    int
}

// WriteObservabilityOverride remaps Grafana / Alloy host ports (loopback-bound).
func WriteObservabilityOverride(path string, p ObservabilityPorts) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	body := fmt.Sprintf(`# Generated by plat5 CLI — do not edit
services:
  grafana:
    ports: !override
      - "127.0.0.1:%d:3000"
  alloy:
    ports: !override
      - "127.0.0.1:%d:4317"
      - "127.0.0.1:%d:4318"
      - "127.0.0.1:%d:12345"
`, p.Grafana, p.OTLPGRPC, p.OTLPHTTP, p.Alloy)
	return os.WriteFile(path, []byte(body), 0o644)
}
